### ISSUE TITLE
mdx_bleach 0.1.1 on PyPI but no release

### ISSUE THREAD

**Issue by lphoward** [Wenzil/mdx_bleach#2]
Need to make a release for 0.1.1

Thanks.

**Comment by Wenzil** [comment]
What repository are you trying to install it from? Also what is the result when running `pip install -v -v -v mdx_bleach`?

**Comment by Wenzil** [comment]
I just created release [0.1.1](https://github.com/Wenzil/mdx_bleach/releases/tag/0.1.1) on github if that's what you were referring to. Let me know if that helps!

**Comment by lphoward** [comment]
Thanks.  easy_install with the restriction "mdx_bleach >= 0.1.1" now succeeds, so the issue is resolved.
